// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/lionng/demo-wire/internal/app/test_struct"
)

// Injectors from wire.go:

func InitializeEvent() test_struct.Event {
	message := test_struct.NewMessage()
	greeter := test_struct.NewGreeter(message)
	event := test_struct.NewEvent(greeter)
	return event
}
